---
- name: Deploy Yolo application
  hosts: all
  become: true
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

  roles:
    - common
    - setup-mongodb
    - backend-deployment
    - frontend-deployment