---
- name: Pull frontend image
  docker_image:
    name: kstella377/stella-yolo-client:v1.0.0
    source: pull

- name: Create frontend container
  docker_container:
    name: yolo-client
    image: kstella377/stella-yolo-client:v1.0.0
    networks:
      - name: app-net
    ports:
      - "3000:3000"
    restart_policy: unless-stopped
    env:
      REACT_APP_API_URL: "http://yolo-backend:5000"
