---
- name: Pull backend image
  docker_image:
    name: kstella377/stella-yolo-backend:v1.0.0
    source: pull

- name: Create backend container
  docker_container:
    name: yolo-backend
    image: kstella377/stella-yolo-backend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    volumes:
      - /home/vagrant/app/backend:/usr/src/app
    environment:
      MONGO_URI: "mongodb://app-mongo:27017/yolo"
      NODE_ENV: "development"
    depends_on:
      - app-mongo
    restart_policy: unless-stopped
